### ISSUE TITLE
When using the 'modelSelector' setting, buildSelector returns circular selector.

### ISSUE THREAD

**Issue by ka-miyake** [strongloop/loopback-connector-cloudant#49] opened 2016-10-25 11:06 UTC
This filter works.

``` javascript
filter = { where:
  { foo: 'foo' }
};
model.find(filter, (err, rslt) => { /* ... */ }); 
```

But this doesn't.

``` javascript
filter = { where: { and: [
  { foo: 'foo' },
  { bar: 'bar' }
]}};
model.find(filter, (err, rslt) => { /* ... */ }); 
```

**Comment by jannyHou** [comment] 2016-11-18 21:49
hmm, it works for me:
Use example https://github.com/strongloop/loopback-example-database
Add another property in model `Account` called `branch`
With some sample data(see reference), try `node .` and open explorer:

Endpoint `GET/ Account` with filter
```
{"where": {"and": [{"email": "email1"}, {"branch": "branch1"}]}}
```
Result:
```json
[
  {
    "email": "email1",
    "branch": "branch1",
    "id": "93f63326e1bbe187e10d873620377013"
  },
  {
    "email": "email1",
    "branch": "branch1",
    "id": "93f63326e1bbe187e10d873620376e5b"
  },
  {
    "email": "email1",
    "branch": "branch1",
    "id": "48eb5295643f29caeae9009d2b3719f4"
  }
]
```

Reference:
```json
[
  {
    "email": "email2",
    "branch": "branch2",
    "id": "c4f513eceaa8647d85fcb99b64294d68"
  },
  {
    "email": "email1",
    "branch": "branch1",
    "id": "93f63326e1bbe187e10d873620377013"
  },
  {
    "email": "email1",
    "branch": "branch1",
    "id": "93f63326e1bbe187e10d873620376e5b"
  },
  {
    "email": "email1",
    "branch": "branch2",
    "id": "bf769780771cbff99efae668242cf8ec"
  },
  {
    "email": "email1",
    "branch": "branch1",
    "id": "48eb5295643f29caeae9009d2b3719f4"
  }
]
```

**Comment by jannyHou** [comment] 2016-11-18 21:50
@ka-miyake It works for me, see my comment in https://github.com/strongloop/loopback-connector-cloudant/issues/49#issuecomment-261650822
If you still run into this issue, please fork https://github.com/strongloop/loopback-sandbox and provide your app to reproduce the error. 

I am closing it now, feel free to reopen it with the sandbox. Thanks.

**Closed by jannyHou** 2016-11-18 21:50 UTC
