### ISSUE TITLE
replaceById in nodejs returns error

### ISSUE THREAD

**Issue by jonascoenen005** [strongloop/loopback-connector-cloudant#46] opened 2016-10-19 09:41 UTC
When using a model and using the method replaceById, it returns the following errror:

Error: The connector cloudant does not support replaceById operation. This is not a bug in LoopBack. Please contact the authors of the connector, preferably via GitHub issues.
    at Function.DataAccessObject.replaceById (C:\secret_path_to_my_nodejsapplication\node_modules\loopback-datasource-juggler\lib\dao.js:2818:15)
    at C:\secret_path_to_my_nodejsapplication\app.js:255:8
    at Layer.handle [as handle_request](C:secret_path_to_my_nodejsapplicationnode_modulesexpresslibrouterlayer.js:95:5)
    at next (C:\secret_path_to_my_nodejsapplication\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (C:\secret_path_to_my_nodejsapplication\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request](C:secret_path_to_my_nodejsapplicationnode_modulesexpresslibrouterlayer.js:95:5)
    at C:\secret_path_to_my_nodejsapplication\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (C:\secret_path_to_my_nodejsapplication\node_modules\express\lib\router\index.js:330:12)
    at next (C:\secret_path_to_my_nodejsapplication\node_modules\express\lib\router\index.js:271:10)
    at C:\secret_path_to_my_nodejs_application\app.js:64:3"

The error declares that i have to contact the authors via github issues, so here i am!

**Comment by superkhau** [comment] 2016-10-19 17:33
@Amir-61 @jannyHou I think this error message isn't pointing at the right place -- "Please contact the authors of the connector (which is us)" should be "Please contact the authors of the driver and link to https://github.com/cloudant/nodejs-cloudant".

@jonascoenen005 Please file an issue with the upstream driver (https://github.com/cloudant/nodejs-cloudant) and ask them to support the replaceById operation.

Closing as resolved since there is nothing to fix here.

**Comment by Amir-61** [comment] 2016-10-19 17:49
@superkhau,
>@Amir-61 @jannyHou I think this error message isn't pointing at the right place -- "Please contact the authors of the connector (which is us)" should be "Please contact the authors of the driver and link to https://github.com/cloudant/nodejs-cloudant".

No they should file a ticket in the GH repo for the connecter in this case `loopback-connector-cloudant`. With that being said @jannyHou has recently added support for `replace` methods in `loopback-connector-cloudant`; however, no release has been done after landing https://github.com/strongloop/loopback-connector-cloudant/pull/34, @jannyHou or @superkhau you may go ahead and release a new NPM version.

CC: @bajtos

**Comment by jannyHou** [comment] 2016-10-19 20:54
@jonascoenen005 @superkhau The patch is under verify, will release it after verify done.
I also updated the answer in related OS issue: http://stackoverflow.com/questions/40111147/updateall-loopback-datasource-does-not-delete-deletions-inside-updated-data/40117755#40117755

Will update there after publishing the new version.

**Comment by superkhau** [comment] 2016-10-19 20:56
@Amir-61 @jannyHou Thanks for clarifying. :+1:

**Comment by bajtos** [comment] 2016-10-20 10:54
> @jannyHou The patch is under verify

Could you please connect the patch to this issue for future reference?

**Comment by bajtos** [comment] 2016-10-20 10:55
@superkhau considering that this issue is waiting for verification, I think `#verify` label is more appropriate than `waiting`. I have applied the label change myself.

**Comment by wtkersting** [comment] 2017-02-28 17:39
Hello, all, I am receiving the same error as OP and couldn't tell from this discussion if anything was resolved.

Here is my error:

{
  "error": {
    "statusCode": 500,
    "name": "Error",
    "message": "The connector cloudant does not support replaceById operation. This is not a bug in LoopBack. Please contact the authors of the connector, preferably via GitHub issues.",
    "stack": "Error: The connector cloudant does not support replaceById operation. This is not a bug in LoopBack. Please contact the authors of the connector, preferably via GitHub issues.\n    at Function.DataAccessObject.replaceById (C:\\Users\\wtker\\Documents\\College\\ECE 485\\TestAPI\\node_modules\\loopback-datasource-juggler\\lib\\dao.js:2871:15)\n    at C:\\Users\\wtker\\Documents\\College\\ECE 485\\TestAPI\\node_modules\\loopback-datasource-juggler\\lib\\dao.js:979:16\n    at C:\\Users\\wtker\\Documents\\College\\ECE 485\\TestAPI\\node_modules\\loopback-datasource-juggler\\lib\\dao.js:2057:5\n    at Object.forward (C:\\Users\\wtker\\AppData\\Roaming\\npm\\node_modules\\apiconnect\\node_modules\\strong-agent\\lib\\proxy.js:92:23)\n    at eval (eval at wrap (C:\\Users\\wtker\\AppData\\Roaming\\npm\\node_modules\\apiconnect\\node_modules\\strong-agent\\lib\\proxy.js:216:20), <anonymous>:3:21)\n    at C:\\Users\\wtker\\Documents\\College\\ECE 485\\TestAPI\\node_modules\\loopback-datasource-juggler\\lib\\dao.js:1984:11\n    at C:\\Users\\wtker\\Documents\\College\\ECE 485\\TestAPI\\node_modules\\loopback-datasource-juggler\\node_modules\\async\\lib\\async.js:396:17\n    at done (C:\\Users\\wtker\\Documents\\College\\ECE 485\\TestAPI\\node_modules\\loopback-datasource-juggler\\node_modules\\async\\lib\\async.js:167:19)\n    at C:\\Users\\wtker\\Documents\\College\\ECE 485\\TestAPI\\node_modules\\loopback-datasource-juggler\\node_modules\\async\\lib\\async.js:40:16\n    at C:\\Users\\wtker\\Documents\\College\\ECE 485\\TestAPI\\node_modules\\loopback-datasource-juggler\\node_modules\\async\\lib\\async.js:393:21\n    at C:\\Users\\wtker\\Documents\\College\\ECE 485\\TestAPI\\node_modules\\loopback-datasource-juggler\\lib\\dao.js:1948:15\n    at C:\\Users\\wtker\\Documents\\College\\ECE 485\\TestAPI\\node_modules\\loopback-datasource-juggler\\node_modules\\async\\lib\\async.js:391:17\n    at C:\\Users\\wtker\\Documents\\College\\ECE 485\\TestAPI\\node_modules\\loopback-datasource-juggler\\node_modules\\async\\lib\\async.js:157:13\n    at _each (C:\\Users\\wtker\\Documents\\College\\ECE 485\\TestAPI\\node_modules\\loopback-datasource-juggler\\node_modules\\async\\lib\\async.js:57:9)\n    at async.each (C:\\Users\\wtker\\Documents\\College\\ECE 485\\TestAPI\\node_modules\\loopback-datasource-juggler\\node_modules\\async\\lib\\async.js:156:9)\n    at _asyncMap (C:\\Users\\wtker\\Documents\\College\\ECE 485\\TestAPI\\node_modules\\loopback-datasource-juggler\\node_modules\\async\\lib\\async.js:390:13)"
  }
}

**Comment by kjdelisle** [comment] 2017-05-24 15:43
This will be out when 2.0 is released.

**Comment by kjdelisle** [comment] 2017-08-23 13:25
@jonascoenen005 
2.0.2 is out! Closing.

**Closed by kjdelisle** 2017-08-23 13:25 UTC
Labels: team-apex, to-be-released
