### ISSUE TITLE
Find query does not return the cloudant bookmark field

### ISSUE THREAD

**Issue by flam312** [strongloop/loopback-connector-cloudant#3] opened 2016-02-23 18:37 UTC
I am using the loopback model find function with the loopback-connector for cloudant. The number of models returned are always <= 200. Upon further investigation I found that this is a limitation imposed by cloudant's query.

https://developer.ibm.com/answers/questions/233525/nodered-cloudant-using-cloudant-node/
https://docs.cloudant.com/cloudant_query.html#finding-documents-using-an-index

The bookmark field is used to for paging through the result sets each of which being a max of 200 rows. 

When debugging the Find matching model instances by filter code in lib\cloudant.js it looks like the query results return both a doc and bookmark field. However, the results.doc is the only thing that is callback. 

Is there a way to have a filtered query result of greater than 200 or use the bookmark to page through in the current connector implementation?

**Comment by bwghughes** [comment] 2016-03-02 16:41
@flam312 Any update on this - did you find a work around?

**Comment by flam312** [comment] 2016-03-02 18:13
@bwghughes I did find a work around by using the loopback skip filter.

https://docs.strongloop.com/display/public/LB/Skip+filter

I basically have a recursive function that executes the same query using the skip filter to page through the results. However, I feel that the connector should be doing this and returning the total amount for us.

**Comment by snowch** [comment] 2016-03-02 22:20
@tonyffrench +1 for resolving this defect as discussed offline today.

**Comment by tonyffrench** [comment] 2016-03-02 22:52
Cloudant Query search limits by design the number of documents returned to 200. I'll investigating a way to surface the bookmark feature. Another alternative maybe to switch between text search vs json search.

**Comment by jmereaux** [comment] 2016-03-03 13:31
+1 For updating the connector so that it returns the whole list of documents if there's more than 200

**Comment by zamrokk** [comment] 2016-03-03 14:07
:+1:

**Comment by noxxious** [comment] 2016-03-03 16:38
+1 here as well.

**Closed** 2016-03-03 17:52 UTC

**Comment by tonyffrench** [comment] 2016-03-03 17:55
Version 1.0.5 should now be out on NPM
