### ISSUE TITLE
corrupted model index? "Error performing text search"

### ISSUE THREAD

**Issue by biancajiang** [strongloop/loopback-connector-cloudant#61] opened 2016-11-25 18:13 UTC
Hi, 

Our loopback APIs with DB queries have been working fine until all of a sudden, APIs involve one particular type of model stops working and always returns "Error performing text search".

e.g. APIs using this query:
``
{"selector":{"loopback__model__name":"package","_id":"bd3728cc668db9d363f0b0d98c448c96"},"use_index":["lb-index-ddoc-package","lb-index-package"],"limit":1,"sort":[{"id:string":"asc"}]}
``

Returns error:
``
Error performing text search: {timeout, {gen_server,call, [<13537.1556.3932>, {prompt, [<<"index_doc">>, {[{<<"_id">>, <<"fb6e036200e23926d5a1de801592f068">>}, {<<"_rev">>, <<"1-1e219de3b35ba0c9a55802a897cc384e">>}, {<<"name">>,<<"IIBCloud">>}, {<<"version">>,<<"0.0.0">>}, {<<"path">>,<<"iib.cloud.ui.web.war">>}, {<<"scanId">>, <<"cfce92cc5425d21cb65dce09553b0ce3">>}, {<<"license_types">>, [<<"Apache-2.0">>,<<"BSD-2-Clause">>, ... ...
``

Seems to me trouble with index ["lb-index-ddoc-package","lb-index-package"].

How to validate and fix this?  This is impacting our production env. Please advice.

**Comment by jannyHou** [comment] 2016-11-25 19:37
@biancajiang I am trying to reproduce your issue, Can you fork https://github.com/strongloop/loopback-sandbox and replace with your code? Include some details like which loopback api you called, or is it a native query directly talk to cloudant datasource. Thanks.

**Comment by biancajiang** [comment] 2016-11-26 23:14
@jannyHou I'm not sure how to recreate it in a test env. w/o sharing the exact DB yet (proprietary data).  The server and DB have been in use and working for months.  Please let me know if you have any idea how to approach this.

Our models include objects like "Scan", "Package" and "LicenseFile".  Scan has many Packages and many LicenseFiles.  Package has many LicenseFiles.

Right now APIs involve packages are returning the 400 Error above like: /api/packages/bd3728cc668db9d363f0b0d98c448c96

Other model APIs w/o packages seem fine, like:
/api/scans/19569d5fa0f68f458772a5f2f1961b91

I can directly access package document with id from cloudant DB.  But any query uses index would give this error.

An example of a Package document:
```
{
  "_id": "bd3728cc668db9d363f0b0d98c448c96",
  "_rev": "1-91ac6ab5ddb4b618f9ed0e7c15f8eac8",
  "name": "oclazyload",
  "version": "1.0.9",
  "path": "bower_components/oclazyload",
  "scanId": "148702417a38a0fb8aa6c0c9b48d17cc",
  "license_types": [
    "MIT"
  ],
  "parentId": "1c77c1bfa27a4e0b44a24728fc40fa01",
  "loopback__model__name": "package"
}
```

An example of a Scan document in the DB:
```
{
  "_id": "19569d5fa0f68f458772a5f2f1961b91",
  "_rev": "2-f8a73ba8102c5e03ee279aa3440b7449",
  "date": "2016-11-21T16:09:16.037Z",
  "project": "lucene-5.5.0",
  "by": "bjiang@us.ibm.com",
  "scan-dir": "/Users/bj/playground/test_data/lucene-5.5.0",
  "scan_time_ms": "253342 ms",
  "directories_scanned": 1658,
  "files_scanned": 25175,
  "packages_found": 1,
  "output_file": "lucene-5.5.0_scanresults_2016-11-21T16-09-16-037Z.json",
  "cli_version": "0.5.19",
  "status": {
    "upload": "Scan Upload Completed successfully."
  },
  "loopback__model__name": "scan"
}
```

**Comment by jannyHou** [comment] 2016-11-29 20:21
I created a simple model `Test` and try get instance from cloudant server:
the query it runs:
```
{"selector":{"loopback__model__name":"Test","_id":"00476caeacb2ab5c33a0fc35c2208e5c"},"use_index":["lb-index-ddoc-Test","lb-index-Test"],"limit":1,"sort":[{"id:string":"asc"}]} +0ms

```

I didn't see problem here with the query itself. It's exactly the same query you use for your package model.

While I do reproduce the error with replicate db you provide me.
I understand that this blocks you badly but I am afraid we could not fix it on our end, because it breaks on that db and loopback-connector-cloudant is only an interface talking to db. Maybe try contact cloudant team who can read and understand the query error.

Good luck!

**Comment by jannyHou** [comment] 2016-11-30 16:10
I am closing this issue since cloudant team would be proper to explain the error message and provide a solution. Thanks for understanding.

**Closed by jannyHou** 2016-11-30 16:10 UTC
Labels: bug, team-apex

**Comment by biancajiang** [comment] 2016-12-09 20:28
This was an issue with Cloudant DB and was resolved.  Thanks!

**Comment by jannyHou** [comment] 2016-12-09 21:45
@biancajiang Glad to hear it's solved :) No problem.
