### ISSUE TITLE
Cannot get (id)

### ISSUE THREAD

**Issue by njemak** [strongloop/loopback-connector-cloudant#4] opened 2016-02-24 08:43 UTC
I define my own id which is string. When I want to get using the get (id) the result is error :
{
  "error": {
    "name": "Error",
    "status": 404,
    "message": "could not find a model with id 1",
    "statusCode": 404,
    "code": "MODEL_NOT_FOUND",
}
}

Same can be happen if I use put(id). But when I only use get, it is works normally.
But when I store the id as full string, i get the result

**Comment by tonyffrench** [comment] 2016-03-03 19:34
@njemak I wonder if this works if the id starts with an alpha character? in that it could be a duplicate of #2

**Closed** 2016-04-21 13:38 UTC
Labels: duplicate
