### ISSUE TITLE
replaceById operation not supported by cloudant connector

### ISSUE THREAD

**Issue by wtkersting** [strongloop/loopback-connector-cloudant#84] opened 2017-03-01 02:32 UTC
### Bug or feature request

- [ ] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

Currently when attempting to do a createOrReplace or any other replace command through my API, I am receiving a 500 error code:

  "error": {
    "statusCode": 500,
    "name": "Error",
    "message": "The connector cloudant does not support replaceById operation. This is not a bug in LoopBack. Please contact the authors of the connector, preferably via GitHub issues.",
    "stack": "Error: The connector cloudant does not support replaceById operation. This is not a bug in LoopBack. Please contact the authors of the connector, preferably via GitHub issues.  ...

I am posting this here wondering if there is a solution to this or if there is a work around available.

### Additional information (Node.js version, LoopBack version, etc)

Node v6.9.4
Loopback v3.10.10

**Comment by dhmlau** [comment] 2017-03-06 15:48
Closing this issue.  Duplicate of https://github.com/strongloop/loopback-connector-cloudant/issues/46.

**Closed by dhmlau** 2017-03-06 15:48 UTC
Labels: duplicate
