### ISSUE TITLE
Filtering on numeric values fails

### ISSUE THREAD

**Issue by timjacobi** [strongloop/loopback-connector-cloudant#2] opened 2016-02-09 12:05 UTC
### Model configuration (simplified)
```JSON
{
  "name": "Record",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "sharedKey": {
      "type": "string",
      "description": "Unique ID",
      "required": true
    }
    ...
  },
  ...
}
```
### Retrieving all records
**`GET https://myhost/api/Records`**
```JSON
[
  {
    "sharedKey":"12345",
    "id":"0266cb32b2afd1d6ea7760ab54981f49",
    "_rev":"2-4cb556a75312172c7730ecbdafb1cd1e"
  },
  {
    "sharedKey":"aString",
    "id":"33c6ca3d10aff422f697322bd1cfddab",
    "_rev":"2-ff30b9a96e4aba1ae36cca785baad2e5"
  }
]
```
### Filtering on the value *aString* returns the expected document
**`GET https://myhost/api/Records?filter[where][sharedKey]=aString`**
```JSON
[
  {
    "sharedKey":"aString",
    "id":"33c6ca3d10aff422f697322bd1cfddab",
    "_rev":"2-ff30b9a96e4aba1ae36cca785baad2e5"
  }
]
```
### Filtering on the value *123456* returns nothing
**`GET https://myhost/api/Records?filter[where][sharedKey]=123456`**
```JSON
[]
```

**Comment by tonyffrench** [comment] 2016-03-02 23:53
@timjacobi seems to be a corner case using Cloudant Query. Running the following query directly against the DB produces the same result:
```
{
    "selector": {
        "loopback__model__name": "Record",
        "sharedKey": "12345"
    },
    "use_index": ["lb-index-ddoc-Record", "lb-index-Record"],
    "sort": [{
        "id:string": "asc"
    }]
}
```
I'll take this up with the Cloudant team.

**Comment by jmereaux** [comment] 2016-03-03 13:33
+1

**Comment by tonyffrench** [comment] 2016-03-03 15:28
Cloudant team has already produced a fix for this issue and it will be rolling out soon. I'm currently testing   against an internal cluster and all looks good.

**Comment by timjacobi** [comment] 2016-03-03 17:58
Super. Thanks for doing the correspondence and testing. Is the issue in cloudant tracked publicly?

**Comment by srinivas-os** [comment] 2016-04-06 10:36
I have this issue as well. How can I get the fix? Should I update cloudant or the connector or both?

**Comment by tonyffrench** [comment] 2016-04-11 14:53
@srinivas-os the fix requires a new version of the Cloudant server. The Cloudant team are working on rolling out the fix, I spoke with them last week on the progress. Thanks for your patience.

**Comment by tonyffrench** [comment] 2016-04-21 13:37
I've just confirmed this is now fixed with Cloudant version {"couchdb":"Welcome","version":"1.0.2","cloudant_build":"**2579**"}

**Closed** 2016-04-21 13:38 UTC
Labels: bug

**Comment by srinivas-os** [comment] 2016-04-21 14:26
@tonyffrench How do I find what version I have? And would the fix be rolled out to all cloudant servers automatically?
